### PR TITLE
Set Build Metadata file path as an action input

### PR DESCRIPTION
**Pull request by jprinet**

### CODE REVIEW

**Review by gsmet — COMMENTED** [review]
I think it would be better if your action made the path an output and we made it an input for this action. That would be more future proof. 

WDYT?

**Comment by jprinet** [comment]
Sure let me take a look at this

**Comment by jprinet** [comment]
I added the file path as an extra input to the action

**Comment by jprinet** [comment]
I created this PR to apply it to Quarkus build when this one will be merged
https://github.com/quarkusio/quarkus/pull/37773

**Review by gsmet — APPROVED** [review]

**Pull request merged**
